Make showProgress viewId optional
posit-dev/publisher pull request #1979
Opened 2024-07-17 00:47 UTC by dotNomad

PR feedback follow-up. Moves the `viewId` param for `showProgress` to make it optional.

2024-07-17 22:40 UTC, sagerb approved these changes
I have mixed feelings about this change. I liked the fact that you had your think about where the progress indicator was best shown, vs doing it as an afterthought (which is how I often think of optional parameters). 

We did have it optional in prior art, so I guess I'm ok with this change. The existing calls to this helper function all provide the viewId, so the impact here is really only on new code.

I'll approve it, but when you have a chance, let's discuss a bit.

Thanks!

2024-07-17 23:15 UTC, dotNomad commented
> I have mixed feelings about this change. I liked the fact that you had your think about where the progress indicator was best shown, vs doing it as an afterthought (which is how I often think of optional parameters).

It was technically already option since it was typed as `viewId: string | undefined`. I'm totally fine requiring a `viewId` in the function calls, and think that would provide a nice benefit.

2024-07-18 21:07 UTC, sagerb commented
> It was technically already option since it was typed as `viewId: string | undefined`. I'm totally fine requiring a `viewId` in the function calls, and think that would provide a nice benefit.

Glad to hear it. Yes, let's require the `viewId` in the function calls then.

2024-07-18 21:10 UTC, sagerb requested changes
We agreed to make the change, so let's make the change within this PR.

I can make these changes for you, since I know you're busy with user testing.

2024-07-18 22:55 UTC, sagerb commented
I've pushed a commit which removes the optionality of the viewID within Show Progress. https://github.com/posit-dev/publisher/pull/1979/commits/08ef450219aade47983a3964f60905f086e3af30

@dotNomad Perhaps you could review those changes?

2024-07-18 22:59 UTC, sagerb approved these changes
@dotNomad code looks good.. Would like to have him review the couple of commits which I contributed before it is merged.

2024-07-19 19:40 UTC, dotNomad reviewed
I think I caught one incorrect reference.

2024-07-19 19:40 UTC, dotNomad commented on extensions/vscode/src/views/credentials.ts
> +      Views.Configurations,
Should this be `Views.Credentials`?

2024-07-22 21:37 UTC, sagerb commented on extensions/vscode/src/views/credentials.ts
> +      Views.Configurations,
Yes. I've pushed an update.

2024-07-22 21:47 UTC, merged